// api/niche.mjs — 1 fichier = 48 pages niches SEO + page de partage universelle
var NICHES = {
  tatouage: {
    fr: { title: "Tatouage IA Gratuit : Créez votre design en 10 secondes (2026)", meta: "Générateur de tatouages IA gratuit. 3 essais sans inscription. Styles réaliste, tribal, aquarelle, géométrique. Libres de droits.", h1: "Tatouage IA gratuit : votre design en 10 secondes", intro: "Trouver le tatouage parfait prend des heures. Avec IA Pixora, décrivez votre idée et obtenez 4 designs uniques en 10 secondes. Gratuit, sans inscription.", h2a: "Comment créer un tatouage avec l'IA ?", steps: ["Décrivez votre idée en une phrase", "Choisissez un style (réaliste, tribal, aquarelle)", "Générez 4 variations instantanément", "Téléchargez votre design favori"], h2b: "Exemples de prompts tatouage", prompts: ["Loup géométrique, dotwork, noir et gris, fond blanc", "Rose aquarelle avec papillon, couleurs vives", "Crâne mexicain jour des morts, détaillé", "Dragon japonais traditionnel, irezumi"], faq: [["Le générateur est-il gratuit ?", "Oui, 3 essais sans inscription."], ["Utilisable chez un tatoueur ?", "Oui, libres de droits."], ["Faut-il un compte ?", "Non, 3 générations sans compte."]] },
    en: { title: "Free AI Tattoo Generator: Create Your Design in 10 Seconds (2026)", meta: "Free AI tattoo generator. 3 tries, no signup. Realistic, tribal, watercolor, geometric. Royalty-free.", h1: "Free AI tattoo: your design in 10 seconds", intro: "Finding the perfect tattoo takes hours. With IA Pixora, describe your idea and get 4 unique designs in 10 seconds. Free, no signup.", h2a: "How to create a tattoo with AI?", steps: ["Describe your idea in one sentence", "Pick a style (realistic, tribal, watercolor)", "Generate 4 variations instantly", "Download your favorite"], h2b: "Tattoo prompt examples", prompts: ["Geometric wolf, dotwork, black and grey, white background", "Watercolor rose with butterfly, vivid colors", "Mexican day of the dead skull, detailed", "Traditional japanese dragon, irezumi"], faq: [["Is it free?", "Yes, 3 tries without signup."], ["Usable at a tattoo shop?", "Yes, royalty-free."], ["Need an account?", "No, 3 generations free."]] },
    es: { title: "Tatuaje IA Gratis: Crea tu diseño en 10 segundos (2026)", meta: "Generador de tatuajes IA gratuito. 3 pruebas sin registro. Realista, tribal, acuarela, geométrico. Libres de derechos.", h1: "Tatuaje IA gratis: tu diseño en 10 segundos", intro: "Encontrar el tatuaje perfecto lleva horas. Con IA Pixora, describe tu idea y obtén 4 diseños únicos en 10 segundos. Gratis, sin registro.", h2a: "¿Cómo crear un tatuaje con IA?", steps: ["Describe tu idea en una frase", "Elige un estilo (realista, tribal, acuarela)", "Genera 4 variaciones al instante", "Descarga tu favorito"], h2b: "Ejemplos de prompts de tatuaje", prompts: ["Lobo geométrico, dotwork, negro y gris, fondo blanco", "Rosa acuarela con mariposa, colores vivos", "Calavera mexicana día de los muertos, detallada", "Dragón japonés tradicional, irezumi"], faq: [["¿Es gratis?", "Sí, 3 pruebas sin registro."], ["¿Usable en un estudio?", "Sí, libres de derechos."], ["¿Necesito cuenta?", "No, 3 generaciones gratis."]] }
  },
  avatar: {
    fr: { title: "Avatar Pro IA Gratuit : Photo professionnelle en 10 secondes (2026)", meta: "Créez votre avatar professionnel par IA. Idéal LinkedIn, CV, WhatsApp. 3 essais sans inscription.", h1: "Avatar pro IA gratuit : votre photo professionnelle", intro: "Une photo pro coûte cher en studio. L'IA génère votre avatar professionnel en 10 secondes. Gratuit, sans inscription.", h2a: "Comment créer un avatar pro avec l'IA ?", steps: ["Décrivez votre apparence et style", "Choisissez un fond (bureau, studio, uni)", "Générez 4 portraits qualité studio", "Téléchargez votre avatar"], h2b: "Exemples de prompts avatar", prompts: ["Portrait pro, costume sombre, fond bureau flou", "Avatar LinkedIn, sourire confiant, fond gris", "Photo pro femme, tailleur bleu, lumière naturelle", "Portrait corporate, chemise blanche, 8K"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Utilisable sur LinkedIn ?", "Oui, libre de droits."], ["Qualité CV ?", "Oui, qualité studio."]] },
    en: { title: "Free Pro AI Avatar: Professional Photo in 10 Seconds (2026)", meta: "Create your professional AI avatar. Perfect for LinkedIn, CV, WhatsApp. 3 tries, no signup.", h1: "Free pro AI avatar: your professional photo", intro: "A pro photo is expensive. AI generates your professional avatar in 10 seconds. Free, no signup.", h2a: "How to create a pro avatar with AI?", steps: ["Describe your look and style", "Pick a background (office, studio, solid)", "Generate 4 studio portraits", "Download your avatar"], h2b: "Avatar prompt examples", prompts: ["Pro portrait, dark suit, blurred office", "LinkedIn avatar, confident smile, grey background", "Business woman, blue blazer, natural light", "Corporate portrait, white shirt, 8K"], faq: [["Free?", "Yes, 3 tries without signup."], ["Usable on LinkedIn?", "Yes, royalty-free."], ["Good for a CV?", "Yes, studio quality."]] },
    es: { title: "Avatar Pro IA Gratis: Foto profesional en 10 segundos (2026)", meta: "Crea tu avatar profesional con IA. Ideal LinkedIn, CV, WhatsApp. 3 pruebas sin registro.", h1: "Avatar pro IA gratis: tu foto profesional", intro: "Una foto pro cuesta caro. La IA genera tu avatar profesional en 10 segundos. Gratis, sin registro.", h2a: "¿Cómo crear un avatar pro con IA?", steps: ["Describe tu aspecto y estilo", "Elige un fondo (oficina, estudio, liso)", "Genera 4 retratos calidad estudio", "Descarga tu avatar"], h2b: "Ejemplos de prompts de avatar", prompts: ["Retrato pro, traje oscuro, oficina desenfocada", "Avatar LinkedIn, sonrisa segura, fondo gris", "Foto pro mujer, blazer azul, luz natural", "Retrato corporativo, camisa blanca, 8K"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Usable en LinkedIn?", "Sí, libre de derechos."], ["¿Sirve para CV?", "Sí, calidad estudio."]] }
  },
  anime: {
    fr: { title: "Anime IA Gratuit : Créez votre personnage en 10 secondes (2026)", meta: "Générateur anime IA gratuit. Styles Ghibli, shonen, kawaii, cyberpunk. 3 essais sans inscription.", h1: "Anime IA gratuit : votre personnage", intro: "Créez votre personnage anime unique en 10 secondes. Styles Ghibli, shonen, kawaii, cyberpunk. Gratuit, sans inscription.", h2a: "Comment créer un personnage anime ?", steps: ["Décrivez votre personnage", "Choisissez une ambiance", "Générez 4 variations", "Téléchargez votre personnage"], h2b: "Exemples de prompts anime", prompts: ["Personnage Ghibli, pastel, cerisiers", "Héros shonen, cheveux argentés, aura électrique", "Personnage kawaii, chibi, fond rose", "Anime cyberpunk, néons, ville nocturne"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Usage commercial ?", "Oui, libre de droits."], ["Quels styles ?", "Ghibli, shonen, kawaii, cyberpunk."]] },
    en: { title: "Free AI Anime: Create Your Character in 10 Seconds (2026)", meta: "Free AI anime generator. Ghibli, shonen, kawaii, cyberpunk. 3 tries, no signup.", h1: "Free AI anime: your character", intro: "Create your unique anime character in 10 seconds. Ghibli, shonen, kawaii, cyberpunk. Free, no signup.", h2a: "How to create an anime character?", steps: ["Describe your character", "Pick a mood", "Generate 4 variations", "Download your character"], h2b: "Anime prompt examples", prompts: ["Ghibli character, pastel, cherry blossoms", "Shonen hero, silver hair, electric aura", "Kawaii character, chibi, pink background", "Cyberpunk anime, neon, night city"], faq: [["Free?", "Yes, 3 tries without signup."], ["Commercial use?", "Yes, royalty-free."], ["Which styles?", "Ghibli, shonen, kawaii, cyberpunk."]] },
    es: { title: "Anime IA Gratis: Crea tu personaje en 10 segundos (2026)", meta: "Generador de anime IA gratuito. Ghibli, shonen, kawaii, cyberpunk. 3 pruebas sin registro.", h1: "Anime IA gratis: tu personaje", intro: "Crea tu personaje de anime único en 10 segundos. Ghibli, shonen, kawaii, cyberpunk. Gratis, sin registro.", h2a: "¿Cómo crear un personaje anime?", steps: ["Describe tu personaje", "Elige un ambiente", "Genera 4 variaciones", "Descarga tu personaje"], h2b: "Ejemplos de prompts de anime", prompts: ["Personaje Ghibli, pastel, cerezos", "Héroe shonen, pelo plateado, aura eléctrica", "Personaje kawaii, chibi, fondo rosa", "Anime cyberpunk, neones, ciudad nocturna"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Uso comercial?", "Sí, libre de derechos."], ["¿Qué estilos?", "Ghibli, shonen, kawaii, cyberpunk."]] }
  },
  logo: {
    fr: { title: "Logo IA Gratuit : Logo professionnel en 10 secondes (2026)", meta: "Générateur de logos IA gratuit. Minimaliste, géométrique, vintage. 3 essais sans inscription.", h1: "Logo IA gratuit : votre logo pro", intro: "Un logo pro coûte des centaines d'euros. L'IA génère votre logo en 10 secondes. Gratuit, libre de droits.", h2a: "Comment créer un logo avec l'IA ?", steps: ["Décrivez votre activité", "Choisissez un type", "Générez 4 propositions", "Téléchargez votre logo"], h2b: "Exemples de prompts logo", prompts: ["Logo minimaliste café, tasse géométrique", "Logo vintage barbier, cercle, rétro", "Logo montagne, lignes fines, moderne", "Logo tech, dégradé bleu, simple"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Usage entreprise ?", "Oui, libre de droits."], ["Haute résolution ?", "Oui, prête à l'emploi."]] },
    en: { title: "Free AI Logo: Professional Logo in 10 Seconds (2026)", meta: "Free AI logo generator. Minimalist, geometric, vintage. 3 tries, no signup.", h1: "Free AI logo: your pro logo", intro: "A pro logo costs hundreds. AI generates your logo in 10 seconds. Free, royalty-free.", h2a: "How to create a logo with AI?", steps: ["Describe your business", "Pick a type", "Generate 4 proposals", "Download your logo"], h2b: "Logo prompt examples", prompts: ["Minimalist coffee logo, geometric cup", "Vintage barber logo, circle, retro", "Mountain logo, thin lines, modern", "Tech logo, blue gradient, simple"], faq: [["Free?", "Yes, 3 tries without signup."], ["Business use?", "Yes, royalty-free."], ["High resolution?", "Yes, ready to use."]] },
    es: { title: "Logo IA Gratis: Logo profesional en 10 segundos (2026)", meta: "Generador de logos IA gratuito. Minimalista, geométrico, vintage. 3 pruebas sin registro.", h1: "Logo IA gratis: tu logo pro", intro: "Un logo pro cuesta cientos. La IA genera tu logo en 10 segundos. Gratis, libre de derechos.", h2a: "¿Cómo crear un logo con IA?", steps: ["Describe tu negocio", "Elige un tipo", "Genera 4 propuestas", "Descarga tu logo"], h2b: "Ejemplos de prompts de logo", prompts: ["Logo minimalista café, taza geométrica", "Logo vintage barbería, círculo, retro", "Logo montaña, líneas finas, moderno", "Logo tech, degradado azul, simple"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Uso empresa?", "Sí, libre de derechos."], ["¿Alta resolución?", "Sí, lista para usar."]] }
  },
  animaux: {
    fr: { title: "Animaux IA Royaux : Portrait majestueux de votre animal (2026)", meta: "Transformez votre animal en portrait royal par IA. Chat, chien, cheval. Gratuit, 3 essais.", h1: "Animaux IA royaux : portrait majestueux", intro: "Transformez votre chat ou chien en roi de la Renaissance. Style viral. Gratuit, sans inscription.", h2a: "Comment créer un portrait royal ?", steps: ["Décrivez votre animal", "Choisissez un costume", "Générez 4 portraits", "Téléchargez et partagez"], h2b: "Exemples de prompts", prompts: ["Chat en roi Renaissance, couronne dorée", "Chien général napoléonien, uniforme", "Cheval royal, armure dorée, épique", "Lapin reine victorienne, élégant"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Bon cadeau ?", "Oui, très populaire."], ["Quels animaux ?", "Chats, chiens, chevaux, lapins."]] },
    en: { title: "Royal AI Animals: Majestic Portrait of Your Pet (2026)", meta: "Turn your pet into a royal AI portrait. Cat, dog, horse. Free, 3 tries.", h1: "Royal AI animals: majestic portrait", intro: "Turn your cat or dog into a Renaissance king. Viral style. Free, no signup.", h2a: "How to create a royal portrait?", steps: ["Describe your pet", "Pick a costume", "Generate 4 portraits", "Download and share"], h2b: "Prompt examples", prompts: ["Cat as Renaissance king, golden crown", "Dog napoleonic general, uniform", "Royal horse, golden armor, epic", "Rabbit victorian queen, elegant"], faq: [["Free?", "Yes, 3 tries without signup."], ["Good gift?", "Yes, very popular."], ["Which animals?", "Cats, dogs, horses, rabbits."]] },
    es: { title: "Animales IA Reales: Retrato majestuoso de tu mascota (2026)", meta: "Convierte tu mascota en retrato real con IA. Gato, perro, caballo. Gratis, 3 pruebas.", h1: "Animales IA reales: retrato majestuoso", intro: "Convierte a tu gato o perro en rey del Renacimiento. Estilo viral. Gratis, sin registro.", h2a: "¿Cómo crear un retrato real?", steps: ["Describe tu mascota", "Elige un disfraz", "Genera 4 retratos", "Descarga y comparte"], h2b: "Ejemplos de prompts", prompts: ["Gato rey Renacimiento, corona dorada", "Perro general napoleónico, uniforme", "Caballo real, armadura dorada, épico", "Conejo reina victoriana, elegante"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Buen regalo?", "Sí, muy popular."], ["¿Qué animales?", "Gatos, perros, caballos, conejos."]] }
  },
  "fond-ecran": {
    fr: { title: "Fond d'Écran IA 4K Gratuit : Wallpapers uniques (2026)", meta: "Générateur de fonds d'écran IA 4K. Paysages, abstract, cyberpunk, espace. 3 essais gratuits.", h1: "Fond d'écran IA 4K gratuit", intro: "L'IA crée ton fond d'écran unique en 4K : paysages, abstract, cyberpunk, espace. Gratuit, sans inscription.", h2a: "Comment créer un wallpaper 4K ?", steps: ["Décris ton ambiance", "Choisis le format (16:9 ou portrait)", "Génère 4 wallpapers", "Télécharge en haute résolution"], h2b: "Exemples de prompts", prompts: ["Montagne enneigée, lever du soleil, 8K", "Ville cyberpunk, néons violets, pluie", "Nébuleuse violette, espace profond", "Forêt enchantée, lucioles, féerique"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Quelle résolution ?", "4K téléphone et écran."], ["Partageable ?", "Oui, libres de droits."]] },
    en: { title: "Free 4K AI Wallpaper: Unique Wallpapers (2026)", meta: "Free 4K AI wallpaper generator. Landscapes, abstract, cyberpunk, space. 3 free tries.", h1: "Free 4K AI wallpaper", intro: "AI creates your unique 4K wallpaper: landscapes, abstract, cyberpunk, space. Free, no signup.", h2a: "How to create a 4K wallpaper?", steps: ["Describe your mood", "Pick format (16:9 or portrait)", "Generate 4 wallpapers", "Download in high resolution"], h2b: "Prompt examples", prompts: ["Snowy mountain, sunrise, 8K", "Cyberpunk city, purple neon, rain", "Purple nebula, deep space", "Enchanted forest, fireflies, magical"], faq: [["Free?", "Yes, 3 tries without signup."], ["What resolution?", "4K phone and desktop."], ["Shareable?", "Yes, royalty-free."]] },
    es: { title: "Fondo de Pantalla IA 4K Gratis: Wallpapers únicos (2026)", meta: "Generador de fondos de pantalla IA 4K. Paisajes, abstracto, cyberpunk, espacio. 3 pruebas gratis.", h1: "Fondo de pantalla IA 4K gratis", intro: "La IA crea tu fondo único en 4K: paisajes, abstracto, cyberpunk, espacio. Gratis, sin registro.", h2a: "¿Cómo crear un wallpaper 4K?", steps: ["Describe tu ambiente", "Elige formato (16:9 o vertical)", "Genera 4 wallpapers", "Descarga en alta resolución"], h2b: "Ejemplos de prompts", prompts: ["Montaña nevada, amanecer, 8K", "Ciudad cyberpunk, neones violetas, lluvia", "Nebulosa violeta, espacio profundo", "Bosque encantado, luciérnagas, mágico"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Qué resolución?", "4K móvil y PC."], ["¿Compartible?", "Sí, libres de derechos."]] }
  },
  coloriage: {
    fr: { title: "Coloriage IA Gratuit : Pages à colorier uniques (2026)", meta: "Générateur de coloriages IA. Mandalas, animaux, enfants, adultes. 3 essais gratuits. Imprimez HD.", h1: "Coloriage IA gratuit : pages uniques", intro: "Créez des coloriages uniques pour enfants et adultes. Imprimez en haute qualité. Gratuit, sans inscription.", h2a: "Comment créer un coloriage ?", steps: ["Choisis un thème", "Demande un contour noir et blanc", "Génère 4 pages", "Imprime en HD"], h2b: "Exemples de prompts", prompts: ["Mandala floral, contour noir et blanc", "Dinosaure mignon, contour simple", "Princesse avec château, contour fin", "Forêt, contour noir et blanc, adultes"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Imprimable ?", "Oui, haute résolution."], ["Enfants et adultes ?", "Oui, tous niveaux."]] },
    en: { title: "Free AI Coloring Pages: Unique Printables (2026)", meta: "Free AI coloring generator. Mandalas, animals, kids, adults. 3 tries. Print HD.", h1: "Free AI coloring: unique pages", intro: "Create unique coloring pages for kids and adults. Print in high quality. Free, no signup.", h2a: "How to create a coloring page?", steps: ["Pick a theme", "Ask for black and white outline", "Generate 4 pages", "Print in HD"], h2b: "Prompt examples", prompts: ["Floral mandala, black and white outline", "Cute dinosaur, simple outline", "Princess with castle, thin outline", "Forest, black and white, adults"], faq: [["Free?", "Yes, 3 tries without signup."], ["Printable?", "Yes, high resolution."], ["Kids and adults?", "Yes, all levels."]] },
    es: { title: "Colorear IA Gratis: Páginas únicas (2026)", meta: "Generador de colorear IA. Mandalas, animales, niños, adultos. 3 pruebas gratis. Imprime HD.", h1: "Colorear IA gratis: páginas únicas", intro: "Crea colorear únicos para niños y adultos. Imprime en alta calidad. Gratis, sin registro.", h2a: "¿Cómo crear un colorear?", steps: ["Elige un tema", "Pide contorno negro y blanco", "Genera 4 páginas", "Imprime en HD"], h2b: "Ejemplos de prompts", prompts: ["Mandala floral, contorno negro y blanco", "Dinosaurio lindo, contorno simple", "Princesa con castillo, contorno fino", "Bosque, contorno negro y blanco, adultos"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Imprimible?", "Sí, alta resolución."], ["¿Niños y adultos?", "Sí, todos los niveles."]] }
  },
  "miniature-youtube": {
    fr: { title: "Miniature YouTube IA Gratuite : Booste tes clics (2026)", meta: "Générateur de miniatures YouTube IA. Gaming, vlog, business. 3 essais gratuits. Format 16:9.", h1: "Miniature YouTube IA gratuite", intro: "Une bonne miniature = plus de clics. L'IA génère des miniatures pro. Gratuit, sans inscription.", h2a: "Comment créer une miniature ?", steps: ["Décris ta vidéo", "Choisis un style", "Génère 4 miniatures", "Télécharge en 16:9"], h2b: "Exemples de prompts", prompts: ["Gaming, visage surpris, néons, texte bold", "Vlog voyage, paysage épique", "Business, costume, fond sombre", "Tuto, écran lumineux, choqué"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Format YouTube ?", "Oui, 16:9 HD."], ["Texte intégré ?", "Oui, textes accrocheurs."]] },
    en: { title: "Free AI YouTube Thumbnail: Boost Your Clicks (2026)", meta: "AI YouTube thumbnail generator. Gaming, vlog, business. 3 free tries. 16:9.", h1: "Free AI YouTube thumbnail", intro: "A good thumbnail = more clicks. AI generates pro thumbnails. Free, no signup.", h2a: "How to create a thumbnail?", steps: ["Describe your video", "Pick a style", "Generate 4 thumbnails", "Download in 16:9"], h2b: "Prompt examples", prompts: ["Gaming, surprised face, neon, bold text", "Travel vlog, epic landscape", "Business, suit, dark background", "Tutorial, bright screen, shocked"], faq: [["Free?", "Yes, 3 tries without signup."], ["YouTube format?", "Yes, 16:9 HD."], ["Text included?", "Yes, catchy text."]] },
    es: { title: "Miniatura YouTube IA Gratis: Aumenta clics (2026)", meta: "Generador de miniaturas YouTube IA. Gaming, vlog, business. 3 pruebas gratis. 16:9.", h1: "Miniatura YouTube IA gratis", intro: "Una buena miniatura = más clics. La IA genera miniaturas pro. Gratis, sin registro.", h2a: "¿Cómo crear una miniatura?", steps: ["Describe tu vídeo", "Elige un estilo", "Genera 4 miniaturas", "Descarga en 16:9"], h2b: "Ejemplos de prompts", prompts: ["Gaming, cara sorprendida, neones, texto bold", "Vlog viaje, paisaje épico", "Business, traje, fondo oscuro", "Tutorial, pantalla brillante, shock"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Formato YouTube?", "Sí, 16:9 HD."], ["¿Texto integrado?", "Sí, textos llamativos."]] }
  },
  "couverture-livre": {
    fr: { title: "Couverture de Livre IA Gratuite : Auto-édition KDP (2026)", meta: "Générateur de couvertures de livre IA. Fantasy, thriller, romance. Idéal KDP. 3 essais gratuits.", h1: "Couverture de livre IA gratuite", intro: "Une couverture pro vend ton livre. Idéal Amazon KDP. Gratuit, libre de droits.", h2a: "Comment créer une couverture ?", steps: ["Décris ton genre", "Choisis une ambiance", "Génère 4 couvertures", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Fantasy, dragon, château, épique", "Thriller, silhouette, nuit", "Romance, couple, coucher de soleil", "Science-fiction, espace, vaisseau"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Utilisable KDP ?", "Oui, droits commerciaux."], ["Résolution ?", "HD prête impression."]] },
    en: { title: "Free AI Book Cover: KDP Self-Publishing (2026)", meta: "AI book cover generator. Fantasy, thriller, romance. Perfect KDP. 3 free tries.", h1: "Free AI book cover", intro: "A pro cover sells your book. Perfect for Amazon KDP. Free, royalty-free.", h2a: "How to create a book cover?", steps: ["Describe your genre", "Pick a mood", "Generate 4 covers", "Download in HD"], h2b: "Prompt examples", prompts: ["Fantasy, dragon, castle, epic", "Thriller, silhouette, night", "Romance, couple, sunset", "Sci-fi, space, spaceship"], faq: [["Free?", "Yes, 3 tries without signup."], ["KDP usable?", "Yes, commercial rights."], ["Resolution?", "HD print-ready."]] },
    es: { title: "Portada de Libro IA Gratis: Autoedición KDP (2026)", meta: "Generador de portadas IA. Fantasía, thriller, romance. Ideal KDP. 3 pruebas gratis.", h1: "Portada de libro IA gratis", intro: "Una portada pro vende tu libro. Ideal Amazon KDP. Gratis, libre de derechos.", h2a: "¿Cómo crear una portada?", steps: ["Describe tu género", "Elige un ambiente", "Genera 4 portadas", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Fantasía, dragón, castillo, épico", "Thriller, silueta, noche", "Romance, pareja, atardecer", "Ciencia ficción, espacio, nave"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Usable KDP?", "Sí, derechos comerciales."], ["¿Resolución?", "HD lista impresión."]] }
  },
  decoration: {
    fr: { title: "Décoration Intérieure IA : Visualise ton intérieur (2026)", meta: "Générateur de déco intérieure IA. Salon, chambre, cuisine. Tous styles. 3 essais gratuits.", h1: "Décoration intérieure IA", intro: "Visualise ton intérieur dans tous les styles avant d'acheter. Gratuit, sans inscription.", h2a: "Comment visualiser une déco ?", steps: ["Décris ta pièce", "Choisis un style", "Génère 4 ambiances", "Télécharge et compare"], h2b: "Exemples de prompts", prompts: ["Salon scandinave, bois clair, plantes", "Chambre bohème, rotin, cosy", "Cuisine industrielle, métal noir", "Bureau minimaliste, blanc"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Tous styles ?", "Oui, tous possibles."], ["Réaliste ?", "Oui, photoréaliste."]] },
    en: { title: "AI Interior Design: Visualize Your Home (2026)", meta: "AI interior generator. Living room, bedroom, kitchen. All styles. 3 free tries.", h1: "AI interior design", intro: "Visualize your home in any style before buying. Free, no signup.", h2a: "How to visualize decor?", steps: ["Describe your room", "Pick a style", "Generate 4 moods", "Download and compare"], h2b: "Prompt examples", prompts: ["Scandinavian living room, light wood", "Boho bedroom, rattan, cosy", "Industrial kitchen, black metal", "Minimalist office, white"], faq: [["Free?", "Yes, 3 tries without signup."], ["All styles?", "Yes, all possible."], ["Realistic?", "Yes, photorealistic."]] },    es: { title: "Decoración Interior IA: Visualiza tu hogar (2026)", meta: "Generador de decoración IA. Salón, dormitorio, cocina. Todos estilos. 3 pruebas gratis.", h1: "Decoración interior IA", intro: "Visualiza tu hogar en cualquier estilo antes de comprar. Gratis, sin registro.", h2a: "¿Cómo visualizar decoración?", steps: ["Describe tu habitación", "Elige un estilo", "Genera 4 ambientes", "Descarga y compara"], h2b: "Ejemplos de prompts", prompts: ["Salón nórdico, madera clara", "Dormitorio bohemio, ratán, cosy", "Cocina industrial, metal negro", "Oficina minimalista, blanco"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Todos estilos?", "Sí, todos posibles."], ["¿Realista?", "Sí, fotorrealista."]] }
  },
  nourriture: {
    fr: { title: "Photo de Nourriture IA : Images gourmandes pro (2026)", meta: "Générateur de photos de nourriture IA. Plats, desserts, boissons. Idéal menus. 3 essais gratuits.", h1: "Photo de nourriture IA pro", intro: "Des photos de plats dignes d'un restaurant pour ton menu ou tes réseaux. Gratuit, sans inscription.", h2a: "Comment créer une photo de plat ?", steps: ["Décris ton plat", "Choisis une ambiance", "Génère 4 photos", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Burger gourmet, fromage fondant", "Macarons, pâtisserie élégante", "Pizza artisanale, four à bois", "Smoothie bowl, fruits frais"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Usage menu ?", "Oui, droits commerciaux."], ["Qualité resto ?", "Oui, pro."]] },
    en: { title: "AI Food Photography: Pro Delicious Images (2026)", meta: "AI food photo generator. Dishes, desserts, drinks. Perfect menus. 3 free tries.", h1: "AI food photography pro", intro: "Restaurant-worthy food photos for your menu or social. Free, no signup.", h2a: "How to create a food photo?", steps: ["Describe your dish", "Pick a mood", "Generate 4 photos", "Download in HD"], h2b: "Prompt examples", prompts: ["Gourmet burger, melting cheese", "Macarons, elegant pastry", "Artisan pizza, wood oven", "Smoothie bowl, fresh fruits"], faq: [["Free?", "Yes, 3 tries without signup."], ["Menu use?", "Yes, commercial rights."], ["Restaurant quality?", "Yes, pro."]] },
    es: { title: "Foto de Comida IA: Imágenes deliciosas pro (2026)", meta: "Generador de fotos de comida IA. Platos, postres, bebidas. Ideal menús. 3 pruebas gratis.", h1: "Foto de comida IA pro", intro: "Fotos de platos dignas de restaurante para tu menú o redes. Gratis, sin registro.", h2a: "¿Cómo crear una foto de plato?", steps: ["Describe tu plato", "Elige un ambiente", "Genera 4 fotos", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Hamburguesa gourmet, queso fundido", "Macarons, repostería elegante", "Pizza artesanal, horno de leña", "Smoothie bowl, frutas frescas"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Uso menú?", "Sí, derechos comerciales."], ["¿Calidad resto?", "Sí, pro."]] }
  },
  mode: {
    fr: { title: "Mode IA Gratuite : Créations de vêtements uniques (2026)", meta: "Générateur de mode IA. Tenues, robes, streetwear, haute couture. 3 essais gratuits.", h1: "Mode IA gratuite : créations uniques", intro: "Visualise tes créations de mode : tenues, robes, streetwear. Gratuit, sans inscription.", h2a: "Comment créer un visuel mode ?", steps: ["Décris ta création", "Choisis un style", "Génère 4 visuels", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Robe de soirée élégante, soie", "Streetwear urbain, oversize", "Haute couture, défilé", "Tenue vintage, années 70"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Tous styles ?", "Oui, tous possibles."], ["Usage pro ?", "Oui, libre de droits."]] },
    en: { title: "Free AI Fashion: Unique Clothing Designs (2026)", meta: "AI fashion generator. Outfits, dresses, streetwear, couture. 3 free tries.", h1: "Free AI fashion: unique designs", intro: "Visualize your fashion designs: outfits, dresses, streetwear. Free, no signup.", h2a: "How to create a fashion visual?", steps: ["Describe your design", "Pick a style", "Generate 4 visuals", "Download in HD"], h2b: "Prompt examples", prompts: ["Elegant evening dress, silk", "Urban streetwear, oversize", "Haute couture, runway", "Vintage outfit, 70s"], faq: [["Free?", "Yes, 3 tries without signup."], ["All styles?", "Yes, all possible."], ["Pro use?", "Yes, royalty-free."]] },
    es: { title: "Moda IA Gratis: Diseños de ropa únicos (2026)", meta: "Generador de moda IA. Atuendos, vestidos, streetwear, alta costura. 3 pruebas gratis.", h1: "Moda IA gratis: diseños únicos", intro: "Visualiza tus diseños de moda: atuendos, vestidos, streetwear. Gratis, sin registro.", h2a: "¿Cómo crear un visual de moda?", steps: ["Describe tu diseño", "Elige un estilo", "Genera 4 visuales", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Vestido de noche elegante, seda", "Streetwear urbano, oversize", "Alta costura, pasarela", "Atuendo vintage, años 70"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Todos estilos?", "Sí, todos posibles."], ["¿Uso pro?", "Sí, libre de derechos."]] }
  },
  immobilier: {
    fr: { title: "Immobilier IA : Home staging virtuel gratuit (2026)", meta: "Générateur immobilier IA. Home staging virtuel, aménagement, rendu 3D. 3 essais gratuits.", h1: "Immobilier IA : home staging virtuel", intro: "Valorise tes biens immobiliers avec du home staging virtuel. Gratuit, sans inscription.", h2a: "Comment faire du home staging IA ?", steps: ["Décris la pièce vide", "Choisis un style d'aménagement", "Génère 4 rendus", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Salon vide meublé moderne, lumineux", "Chambre scandinave, cosy", "Cuisine aménagée, contemporaine", "Bureau à domicile, fonctionnel"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Pour agents immo ?", "Oui, idéal vente/location."], ["Réaliste ?", "Oui, photoréaliste."]] },
    en: { title: "AI Real Estate: Free Virtual Home Staging (2026)", meta: "AI real estate generator. Virtual staging, furnishing, 3D render. 3 free tries.", h1: "AI real estate: virtual staging", intro: "Boost your property listings with virtual home staging. Free, no signup.", h2a: "How to do AI home staging?", steps: ["Describe the empty room", "Pick a furnishing style", "Generate 4 renders", "Download in HD"], h2b: "Prompt examples", prompts: ["Empty living room, modern furniture, bright", "Scandinavian bedroom, cosy", "Furnished kitchen, contemporary", "Home office, functional"], faq: [["Free?", "Yes, 3 tries without signup."], ["For agents?", "Yes, ideal sale/rental."], ["Realistic?", "Yes, photorealistic."]] },
    es: { title: "Inmobiliaria IA: Home staging virtual gratis (2026)", meta: "Generador inmobiliario IA. Home staging virtual, amueblado, render 3D. 3 pruebas gratis.", h1: "Inmobiliaria IA: home staging virtual", intro: "Valoriza tus propiedades con home staging virtual. Gratis, sin registro.", h2a: "¿Cómo hacer home staging IA?", steps: ["Describe la habitación vacía", "Elige un estilo", "Genera 4 renders", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Salón vacío amueblado moderno, luminoso", "Dormitorio nórdico, cosy", "Cocina amueblada, contemporánea", "Oficina en casa, funcional"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Para agentes?", "Sí, ideal venta/alquiler."], ["¿Realista?", "Sí, fotorrealista."]] }
  },
  espace: {
    fr: { title: "Espace IA Gratuit : Planètes et galaxies en 4K (2026)", meta: "Générateur espace IA. Planètes, nébuleuses, galaxies, sci-fi. 3 essais gratuits. 4K.", h1: "Espace IA gratuit : planètes et galaxies", intro: "Crée des images spatiales épiques : planètes, nébuleuses, galaxies. Gratuit, sans inscription.", h2a: "Comment créer une image espace ?", steps: ["Décris ta scène spatiale", "Choisis un style", "Génère 4 images", "Télécharge en 4K"], h2b: "Exemples de prompts", prompts: ["Planète aux anneaux, nébuleuse violette", "Galaxie spirale, étoiles, profond", "Astronaute sur Mars, réaliste", "Vaisseau spatial, sci-fi, épique"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Résolution 4K ?", "Oui, haute résolution."], ["Usage wallpaper ?", "Oui, parfait fond d'écran."]] },
    en: { title: "Free AI Space: Planets and Galaxies in 4K (2026)", meta: "AI space generator. Planets, nebulas, galaxies, sci-fi. 3 free tries. 4K.", h1: "Free AI space: planets and galaxies", intro: "Create epic space images: planets, nebulas, galaxies. Free, no signup.", h2a: "How to create a space image?", steps: ["Describe your space scene", "Pick a style", "Generate 4 images", "Download in 4K"], h2b: "Prompt examples", prompts: ["Ringed planet, purple nebula", "Spiral galaxy, stars, deep", "Astronaut on Mars, realistic", "Spaceship, sci-fi, epic"], faq: [["Free?", "Yes, 3 tries without signup."], ["4K resolution?", "Yes, high resolution."], ["Wallpaper use?", "Yes, perfect wallpaper."]] },
    es: { title: "Espacio IA Gratis: Planetas y galaxias en 4K (2026)", meta: "Generador espacio IA. Planetas, nebulosas, galaxias, sci-fi. 3 pruebas gratis. 4K.", h1: "Espacio IA gratis: planetas y galaxias", intro: "Crea imágenes espaciales épicas: planetas, nebulosas, galaxias. Gratis, sin registro.", h2a: "¿Cómo crear una imagen espacial?", steps: ["Describe tu escena espacial", "Elige un estilo", "Genera 4 imágenes", "Descarga en 4K"], h2b: "Ejemplos de prompts", prompts: ["Planeta con anillos, nebulosa violeta", "Galaxia espiral, estrellas, profundo", "Astronauta en Marte, realista", "Nave espacial, sci-fi, épico"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Resolución 4K?", "Sí, alta resolución."], ["¿Uso wallpaper?", "Sí, perfecto fondo."]] }
  },
  mariage: {
    fr: { title: "Invitation Mariage IA Gratuite : Créations élégantes (2026)", meta: "Générateur d'invitations de mariage IA. Élégant, floral, vintage, moderne. 3 essais gratuits.", h1: "Invitation mariage IA gratuite", intro: "Crée des invitations de mariage élégantes et uniques. Gratuit, sans inscription.", h2a: "Comment créer une invitation ?", steps: ["Décris ton thème", "Choisis un style", "Génère 4 invitations", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Invitation florale, aquarelle, élégante", "Mariage vintage, doré, romantique", "Invitation moderne, minimaliste", "Mariage champêtre, nature"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Imprimable ?", "Oui, haute résolution."], ["Personnalisable ?", "Oui, tous thèmes."]] },
    en: { title: "Free AI Wedding Invitation: Elegant Designs (2026)", meta: "AI wedding invitation generator. Elegant, floral, vintage, modern. 3 free tries.", h1: "Free AI wedding invitation", intro: "Create elegant and unique wedding invitations. Free, no signup.", h2a: "How to create an invitation?", steps: ["Describe your theme", "Pick a style", "Generate 4 invitations", "Download in HD"], h2b: "Prompt examples", prompts: ["Floral invitation, watercolor, elegant", "Vintage wedding, gold, romantic", "Modern invitation, minimalist", "Rustic wedding, nature"], faq: [["Free?", "Yes, 3 tries without signup."], ["Printable?", "Yes, high resolution."], ["Customizable?", "Yes, all themes."]] },
    es: { title: "Invitación Boda IA Gratis: Diseños elegantes (2026)", meta: "Generador de invitaciones de boda IA. Elegante, floral, vintage, moderno. 3 pruebas gratis.", h1: "Invitación boda IA gratis", intro: "Crea invitaciones de boda elegantes y únicas. Gratis, sin registro.", h2a: "¿Cómo crear una invitación?", steps: ["Describe tu tema", "Elige un estilo", "Genera 4 invitaciones", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Invitación floral, acuarela, elegante", "Boda vintage, dorado, romántico", "Invitación moderna, minimalista", "Boda rústica, naturaleza"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Imprimible?", "Sí, alta resolución."], ["¿Personalizable?", "Sí, todos los temas."]] }
  },
  sticker: {
    fr: { title: "Stickers IA Gratuits : Print-on-demand Etsy (2026)", meta: "Générateur de stickers IA. Print-on-demand, Etsy, Redbubble. Contours découpés. 3 essais gratuits.", h1: "Stickers IA gratuits : print-on-demand", intro: "Crée des stickers pour Etsy, Redbubble, print-on-demand. Gratuit, libre de droits.", h2a: "Comment créer un sticker ?", steps: ["Décris ton sticker", "Choisis un style", "Génère 4 stickers", "Télécharge en HD"], h2b: "Exemples de prompts", prompts: ["Sticker chat mignon, contour blanc", "Sticker café, kawaii, die-cut", "Sticker motivation, typographie", "Sticker animal, aquarelle"], faq: [["Gratuit ?", "Oui, 3 essais sans inscription."], ["Vendable sur Etsy ?", "Oui, libres de droits."], ["Contour découpé ?", "Oui, style die-cut."]] },
    en: { title: "Free AI Stickers: Print-on-demand Etsy (2026)", meta: "AI sticker generator. Print-on-demand, Etsy, Redbubble. Die-cut outlines. 3 free tries.", h1: "Free AI stickers: print-on-demand", intro: "Create stickers for Etsy, Redbubble, print-on-demand. Free, royalty-free.", h2a: "How to create a sticker?", steps: ["Describe your sticker", "Pick a style", "Generate 4 stickers", "Download in HD"], h2b: "Prompt examples", prompts: ["Cute cat sticker, white outline", "Coffee sticker, kawaii, die-cut", "Motivation sticker, typography", "Animal sticker, watercolor"], faq: [["Free?", "Yes, 3 tries without signup."], ["Sellable on Etsy?", "Yes, royalty-free."], ["Die-cut outline?", "Yes, die-cut style."]] },
    es: { title: "Stickers IA Gratis: Print-on-demand Etsy (2026)", meta: "Generador de stickers IA. Print-on-demand, Etsy, Redbubble. Contornos troquelados. 3 pruebas gratis.", h1: "Stickers IA gratis: print-on-demand", intro: "Crea stickers para Etsy, Redbubble, print-on-demand. Gratis, libre de derechos.", h2a: "¿Cómo crear un sticker?", steps: ["Describe tu sticker", "Elige un estilo", "Genera 4 stickers", "Descarga en HD"], h2b: "Ejemplos de prompts", prompts: ["Sticker gato lindo, contorno blanco", "Sticker café, kawaii, troquelado", "Sticker motivación, tipografía", "Sticker animal, acuarela"], faq: [["¿Gratis?", "Sí, 3 pruebas sin registro."], ["¿Vendible en Etsy?", "Sí, libres de derechos."], ["¿Contorno troquelado?", "Sí, estilo die-cut."]] }
  }
};

var UI = {
  fr: { back: "← IA Pixora", try: "Essayer gratuitement", create: "Créer mon image gratuite", gallery: "Voir la galerie publique", faq: "FAQ" },
  en: { back: "← IA Pixora", try: "Try for free", create: "Create my free image", gallery: "View public gallery", faq: "FAQ" },
  es: { back: "← IA Pixora", try: "Probar gratis", create: "Crear mi imagen gratis", gallery: "Ver galería pública", faq: "FAQ" }
};
var FLAGS = { fr: "🇫🇷", en: "🇬🇧", es: "🇪🇸" };

function buildSharePage(imgUrl) {
  var shareUrl = "https://www.iapixora.com/share.html?img=" + encodeURIComponent(imgUrl);
  var text = "Regarde cette image créée avec IA Pixora 🎨";
  var e = encodeURIComponent;
  var su = e(shareUrl), tx = e(text), im = e(imgUrl);
  var nets = [
    ["💬 WhatsApp", "https://wa.me/?text=" + tx + "%20" + su],
    ["✈️ Telegram", "https://t.me/share/url?url=" + su + "&text=" + tx],
    ["🐦 X / Twitter", "https://twitter.com/intent/tweet?text=" + tx + "&url=" + su],    ["📘 Facebook", "https://www.facebook.com/sharer/sharer.php?u=" + su],
    ["💼 LinkedIn", "https://www.linkedin.com/sharing/share-offsite/?url=" + su],
    ["📌 Pinterest", "https://www.pinterest.com/pin/create/button/?url=" + su + "&media=" + im + "&description=" + tx],
    ["👽 Reddit", "https://www.reddit.com/submit?url=" + su + "&title=" + tx],
    ["🧵 Threads", "https://www.threads.net/intent/post?text=" + tx + "%20" + su],
    ["🦋 Bluesky", "https://bsky.app/intent/compose?text=" + tx + "%20" + su],
    ["🐘 Mastodon", "https://mastodonshare.com/?text=" + tx + "&url=" + su],
    ["🟢 LINE", "https://social-plugins.line.me/lineit/share?url=" + su],
    ["🔵 VK", "https://vk.com/share.php?url=" + su],
    ["🟠 Odnoklassniki", "https://connect.ok.ru/offer?url=" + su],
    ["🔴 Weibo", "https://service.weibo.com/share/share.php?url=" + su + "&title=" + tx],
    ["🟡 Qzone", "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=" + su + "&title=" + tx],
    ["📓 Tumblr", "https://www.tumblr.com/share/link?url=" + su + "&name=" + tx],
    ["🅱️ Blogger", "https://www.blogger.com/blog-this.g?u=" + su + "&n=" + tx],
    ["📰 Flipboard", "https://share.flipboard.com/bookmarklet/popout?url=" + su + "&title=" + tx],
    ["🗞️ Pocket", "https://getpocket.com/save?url=" + su],
    ["✉️ Email", "mailto:?subject=" + tx + "&body=" + su],
    ["📱 SMS", "sms:?&body=" + tx + "%20" + su]
  ];
  var btns = "<button class='net' data-u='" + shareUrl + "' onclick='navigator.clipboard.writeText(this.getAttribute(\"data-u\"))'>📋 Copier</button>";
  for (var i = 0; i < nets.length; i++) {
    btns += "<a class='net' target='_blank' rel='noopener' href='" + nets[i][1] + "'>" + nets[i][0] + "</a>";
  }
  return "<!DOCTYPE html><html lang='fr'><head><script async src='https://www.googletagmanager.com/gtag/js?id=G-TDZXXYQRBQ'></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-TDZXXYQRBQ');</script><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1.0'>" +
    "<title>Image partagée | IA Pixora</title>" +
    "<meta name='description' content='Image créée avec IA Pixora, générateur d'images IA gratuit. Créez la vôtre en 10 secondes.'>" +
    "<meta property='og:type' content='website'>" +
    "<meta property='og:title' content='Regarde cette image créée avec IA Pixora'>" +
    "<meta property='og:description' content='Générateur d'images IA gratuit — 3 essais sans inscription. Crée la tienne !'>" +
    "<meta property='og:image' content='" + imgUrl + "'>" +
    "<meta property='og:image:width' content='1024'>" +
    "<meta property='og:image:height' content='768'>" +
    "<meta name='twitter:card' content='summary_large_image'>" +
    "<meta name='twitter:title' content='Regarde cette image créée avec IA Pixora'>" +
    "<meta name='twitter:description' content='Générateur d'images IA gratuit — 3 essais sans inscription.'>" +
    "<meta name='twitter:image' content='" + imgUrl + "'>" +
    "<style>body{background:#050507;color:#FAFAFA;font-family:Inter,sans-serif;margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box}.card{max-width:560px;width:100%;text-align:center}.logo{font-weight:800;background:linear-gradient(135deg,#8B5CF6,#EC4899);-webkit-background-clip:text;-webkit-text-fill-color:transparent}img{width:100%;border-radius:16px;border:1px solid rgba(139,92,246,.4);margin:16px 0}.btn{display:inline-block;margin:6px;padding:14px 24px;border-radius:12px;text-decoration:none;font-weight:700}.primary{background:linear-gradient(135deg,#8B5CF6,#EC4899);color:#fff}.ghost{border:1px solid rgba(139,92,246,.5);color:#c4b5fd}.nets{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin:12px 0}.net{padding:10px 14px;border-radius:999px;background:rgba(139,92,246,.15);border:1px solid rgba(139,92,246,.4);color:#c4b5fd;text-decoration:none;font-size:.85rem;cursor:pointer}</style>" +
    "</head><body><div class='card'><div class='logo'>IA Pixora</div>" +
    "<img src='" + imgUrl + "' alt='Image créée avec IA Pixora'>" +
    "<div class='nets'>" + btns + "</div>" +
    "<a class='btn primary' href='https://www.iapixora.com/'>Créer mon image gratuite</a>" +
    "<a class='btn ghost' href='" + imgUrl + "' download>Télécharger</a>" +
    "</div></body></html>";
}

function buildPage(d, lang, niche, allLangs) {
  var ui = UI[lang] || UI.en;
  var langBar = "<p style='margin:12px 0'>";
  for (var i2 = 0; i2 < allLangs.length; i2++) {
    var ll = allLangs[i2];    langBar += "<a href='https://www.iapixora.com/niche/" + ll + "/" + niche + "' style='margin-right:14px;text-decoration:" + (ll === lang ? "underline" : "none") + ";font-weight:700'>" + (FLAGS[ll] || "🌐") + " " + ll.toUpperCase() + "</a>";
  }
  langBar += "</p>";
  var hreflang = "";
  for (var i = 0; i < allLangs.length; i++) {
    var l = allLangs[i];
    hreflang += '<link rel="alternate" hreflang="' + l + '" href="https://www.iapixora.com/niche/' + l + '/' + niche + '">';
  }
  hreflang += '<link rel="alternate" hreflang="x-default" href="https://www.iapixora.com/niche/en/' + niche + '">';
  var faqJson = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": d.faq.map(function (f) { return { "@type": "Question", "name": f[0], "acceptedAnswer": { "@type": "Answer", "text": f[1] } }; }) };
  var stepsHtml = "";
  for (var s = 0; s < d.steps.length; s++) { stepsHtml += "<li><strong>" + (s + 1) + ".</strong> " + d.steps[s] + "</li>"; }
  var promptsHtml = "";
  for (var p = 0; p < d.prompts.length; p++) { promptsHtml += "<li>" + d.prompts[p] + "</li>"; }
  var faqHtml = "";
  for (var f = 0; f < d.faq.length; f++) { faqHtml += "<h3>" + d.faq[f][0] + "</h3><p>" + d.faq[f][1] + "</p>"; }
  return "<!DOCTYPE html><html lang='" + lang + "'><head><script async src='https://www.googletagmanager.com/gtag/js?id=G-TDZXXYQRBQ'></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-TDZXXYQRBQ');</script><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1.0'><title>" + d.title + "</title><meta name='description' content='" + d.meta + "'><link rel='canonical' href='https://www.iapixora.com/niche/" + lang + "/" + niche + "'>" + hreflang + "<script type='application/ld+json'>" + JSON.stringify(faqJson) + "</script><style>body{background:#050507;color:#FAFAFA;font-family:Inter,sans-serif;line-height:1.6;margin:0;padding:20px;max-width:800px;margin:0 auto}h1{color:#8B5CF6}h2{color:#EC4899;margin-top:32px}a{color:#8B5CF6}li{margin:8px 0}.cta{display:inline-block;background:linear-gradient(135deg,#8B5CF6,#EC4899);color:#fff;padding:14px 28px;border-radius:12px;text-decoration:none;font-weight:700;margin:20px 0}</style></head><body>" + langBar + "<p><a href='https://www.iapixora.com'>" + ui.back + "</a></p><h1>" + d.h1 + "</h1><p>" + d.intro + "</p><a class='cta' href='https://www.iapixora.com'>" + ui.try + "</a><h2>" + d.h2a + "</h2><ol>" + stepsHtml + "</ol><h2>" + d.h2b + "</h2><ul>" + promptsHtml + "</ul><h2>" + ui.faq + "</h2>" + faqHtml + "<a class='cta' href='https://www.iapixora.com'>" + ui.create + "</a><p><a href='https://www.iapixora.com/gallery.html'>" + ui.gallery + "</a></p></body></html>";
}

export default function (req, res) {
  try {
    // 🤖 ROUTE ROBOT SEO : liste des niches + prompts (non-indexée)
    if (req.query.list) {
      var out = {};
      for (var k in NICHES) {
        var e2 = NICHES[k].en || NICHES[k].fr || {};
        out[k] = (e2.prompts || []).slice(0, 3);
      }
      res.setHeader("Content-Type", "application/json");
      res.setHeader("X-Robots-Tag", "noindex");
      res.setHeader("Cache-Control", "public, max-age=60");
      res.statusCode = 200;
      res.end(JSON.stringify(out));
      return;
    }
    if (req.query.img) {
      res.setHeader("Content-Type", "text/html; charset=utf-8");
      res.statusCode = 200;
      res.end(buildSharePage(String(req.query.img)));
      return;
    }
    var lang = String(req.query.lang || "fr").toLowerCase();
    var niche = String(req.query.niche || "").toLowerCase();
    var n = NICHES[niche];
    var d = n && n[lang];
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    if (!d) { res.statusCode = 404; res.end("<h1>404</h1><p>Page introuvable. <a href='https://www.iapixora.com'>Retour IA Pixora</a></p>"); return; }
    res.statusCode = 200;
    res.end(buildPage(d, lang, niche, Object.keys(n)));
  } catch (e) { res.statusCode = 500; res.end("Erreur"); }}
