// api/share.js - v3.0: EN/FR complet + 6 images récentes + Like/Comment/Remix
export default async function handler(req, res) {
  let imgUrl = req.query.img || 'https://www.iapixora.com/favicon.png';
  const lang = req.query.lang === 'en' ? 'en' : 'fr';

  async function pick(url) {
    const variants = [url];
    if (url.includes('/gen/F')) variants.push(url.replace('/gen/F', '/gen/'));
    for (const v of variants) {
      try { const r = await fetch(v, { method: 'HEAD' }); if (r.ok) return v; } catch (e) {}
    }
    return url;
  }
  imgUrl = await pick(imgUrl);

  // MODE RAW : og:image preview
  if (req.query.raw === '1' && imgUrl.includes('.r2.dev/')) {
    try {
      const r = await fetch(imgUrl, { headers: { 'User-Agent': 'Mozilla/5.0', 'Accept': 'image/*' } });
      if (r.ok) {
        const ext = imgUrl.split('.').pop().toLowerCase();
        const ct = ext === 'png' ? 'image/png' : (ext === 'jpg' || ext === 'jpeg') ? 'image/jpeg' : 'image/webp';
        const buf = Buffer.from(await r.arrayBuffer());
        res.setHeader('Content-Type', ct);
        res.setHeader('Cache-Control', 'public, max-age=604800');
        return res.status(200).send(buf);
      }
    } catch (e) {}
  }

  const ogUrl = imgUrl.includes('.r2.dev/')
    ? 'https://www.iapixora.com/api/share?img=' + encodeURIComponent(imgUrl) + '&raw=1'
    : imgUrl;

  // Récupérer les 6 images récentes depuis Supabase
  let recentImages = [];
  try {
    const supaUrl = process.env.SUPABASE_URL || '';
    const supaKey = process.env.SUPABASE_ANON_KEY || '';
    if (supaUrl && supaKey) {
      const dbRes = await fetch(`${supaUrl}/rest/v1/creations?select=image_url,prompt&order=created_at.desc&limit=6`, {
        headers: { 'apikey': supaKey, 'Authorization': `Bearer ${supaKey}` }
      });
      if (dbRes.ok) {
        const data = await dbRes.json();
        recentImages = data.filter(i => i.image_url && i.image_url !== imgUrl).slice(0, 6);
      }    }
  } catch (e) {}

  // Fallback si Supabase ne répond pas
  if (recentImages.length === 0) {
    const fallbackIds = [
      '1787312224754-geometric-wolf-dotwork-black-and-grey-wh',
      '1787312235969-geometric-wolf-dotwork-black-and-grey-wh',
      '1787312247891-cyberpunk-city-neon-rain-night',
      '1787312258903-anime-girl-cherry-blossom-sakura',
      '1787312269012-logo-minimalist-mountain-gold',
      '1787312279124-tattoo-dragon-japanese-ink'
    ];
    recentImages = fallbackIds.map(id => ({
      image_url: `https://pub-5df218abc5c34ffe8e2a67276fce23d1.r2.dev/gen/${id}.png`
    }));
  }

  const SITE = 'https://www.iapixora.com';
  const URLS = {
    home: SITE + '/',
    gallery: SITE + '/gallery.html',
    shop: SITE + '/shop.html',
    earn: SITE + '/earn.html',
    profile: SITE + '/profile.html',
    privacy: SITE + '/privacy.html',
    guide: SITE + '/guide.html',
    faq: SITE + '/faq.html'
  };

  const t = {
    fr: {
      title: 'Regarde cette image IA créée avec IA Pixora 🎨',
      desc: 'Cette image a été générée gratuitement avec IA Pixora. Crée la tienne en quelques secondes, sans inscription !',
      btn_create: '✨ Créer mon image gratuite',
      btn_download: 'Télécharger',
      btn_gallery: 'Explorer la galerie',
      btn_shop: 'Boutique',
      btn_earn: 'Gagner des points',
      badge: 'Générée gratuitement sur IA Pixora',
      error: 'Image non disponible',
      more_title: 'Créations récentes de la communauté',
      more_sub: 'Découvre les dernières images générées par nos utilisateurs',
      cta_title: 'Crée ta propre image IA',
      cta_sub: 'Gratuit · Sans inscription · 10 images/jour',
      footer_privacy: 'Confidentialité',
      footer_guide: 'Guide',
      footer_faq: 'FAQ',
      nav_home: 'Accueil',
      nav_gallery: 'Galerie',      nav_shop: 'Boutique',
      nav_profile: 'Mon profil',
      like: 'J\'aime',
      comment: 'Commenter',
      remix: 'Remixer',
      likes_count: 'personnes aiment',
      comments_count: 'commentaires',
      login_to_interact: 'Connecte-toi pour aimer et commenter'
    },
    en: {
      title: 'Check out this AI image made with IA Pixora 🎨',
      desc: 'This image was generated for free with IA Pixora. Create yours in seconds, no signup required!',
      btn_create: '✨ Create my free image',
      btn_download: 'Download',
      btn_gallery: 'Explore gallery',
      btn_shop: 'Shop',
      btn_earn: 'Earn points',
      badge: 'Generated for free on IA Pixora',
      error: 'Image not available',
      more_title: 'Recent community creations',
      more_sub: 'Discover the latest images generated by our users',
      cta_title: 'Create your own AI image',
      cta_sub: 'Free · No signup · 10 images/day',
      footer_privacy: 'Privacy',
      footer_guide: 'Guide',
      footer_faq: 'FAQ',
      nav_home: 'Home',
      nav_gallery: 'Gallery',
      nav_shop: 'Shop',
      nav_profile: 'My profile',
      like: 'Like',
      comment: 'Comment',
      remix: 'Remix',
      likes_count: 'people like this',
      comments_count: 'comments',
      login_to_interact: 'Log in to like and comment'
    }
  }[lang];

  // Générer les 6 cards d'images récentes
  const recentCards = recentImages.map((img, i) => {
    const shareLink = `${SITE}/api/share?img=${encodeURIComponent(img.image_url)}&lang=${lang}`;
    return `<a href="${shareLink}" class="recent-card">
      <img src="${img.image_url}" alt="AI Art ${i+1}" loading="lazy" onerror="this.parentElement.style.display='none'">
    </a>`;
  }).join('\n                ');

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${t.title}</title>
    <meta name="description" content="${t.desc}">
    <link rel="canonical" href="${URLS.home}">
    <link rel="icon" type="image/png" href="${SITE}/favicon.png">
    <link rel="apple-touch-icon" href="${SITE}/favicon.png">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="IA Pixora">
    <meta property="og:url" content="${URLS.home}">
    <meta property="og:title" content="${t.title}">
    <meta property="og:description" content="${t.desc}">
    <meta property="og:image" content="${ogUrl}">
    <meta property="og:image:width" content="1024">
    <meta property="og:image:height" content="1024">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${t.title}">
    <meta name="twitter:description" content="${t.desc}">
    <meta name="twitter:image" content="${ogUrl}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root{--bg:#050507;--surf:rgba(24,24,27,0.6);--surf2:rgba(39,39,42,0.5);--border:rgba(63,63,70,0.5);--prim:#8B5CF6;--sec:#EC4899;--text:#FAFAFA;--muted:#A1A1AA;--green:#10B981;--red:#EF4444;--font:'Inter',sans-serif}
        *{margin:0;padding:0;box-sizing:border-box}
        body{background:var(--bg);color:var(--text);font-family:var(--font);min-height:100dvh;display:flex;flex-direction:column}
        .nav{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.5rem;border-bottom:1px solid var(--border);backdrop-filter:blur(12px);position:sticky;top:0;z-index:100;background:rgba(5,5,7,0.85)}
        .nav-logo{display:flex;align-items:center;gap:0.5rem;text-decoration:none;color:var(--text)}
        .nav-logo svg{width:28px;height:28px}
        .nav-logo span{font-size:1.1rem;font-weight:800;background:linear-gradient(135deg,#fff 20%,var(--prim) 80%);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
        .nav-links{display:flex;gap:1rem;align-items:center}
        .nav-links a{color:var(--muted);text-decoration:none;font-size:0.85rem;font-weight:600;transition:color 0.2s}
        .nav-links a:hover{color:var(--text)}
        .nav-login{padding:0.4rem 1rem;background:rgba(139,92,246,0.15);border:1px solid rgba(139,92,246,0.3);border-radius:8px;color:var(--prim)!important;transition:all 0.2s}
        .nav-login:hover{background:rgba(139,92,246,0.25)!important}
        @media(max-width:600px){.nav-links a:not(.nav-login){display:none}}
        .main{flex:1;display:flex;flex-direction:column;align-items:center;padding:2rem 1rem;gap:2rem}
        .container{max-width:640px;width:100%;display:flex;flex-direction:column;align-items:center;gap:1.5rem}
        .badge-free{display:inline-flex;align-items:center;gap:0.4rem;background:rgba(16,185,129,0.12);border:1px solid rgba(16,185,129,0.25);color:var(--green);font-size:0.75rem;font-weight:700;padding:4px 14px;border-radius:20px}
        .image-wrapper{width:100%;border-radius:20px;overflow:hidden;border:1px solid var(--border);box-shadow:0 20px 60px rgba(139,92,246,0.2);position:relative;background:var(--surf)}
        .image-wrapper img{width:100%;height:auto;display:block;cursor:pointer}

        /* INTERACTION BAR */
        .interaction-bar{display:flex;gap:0.6rem;width:100%;justify-content:center;flex-wrap:wrap}
        .btn-interact{display:inline-flex;align-items:center;gap:0.5rem;padding:0.7rem 1.4rem;background:var(--surf2);border:1px solid var(--border);color:var(--muted);border-radius:12px;font-weight:600;font-size:0.85rem;cursor:pointer;transition:all 0.2s;text-decoration:none}
        .btn-interact:hover{background:rgba(255,255,255,0.1);color:var(--text);border-color:var(--prim)}
        .btn-interact.liked{color:var(--red);border-color:var(--red);background:rgba(239,68,68,0.1)}
        .btn-interact .count{font-size:0.75rem;opacity:0.7}
        .btn-remix{color:var(--prim)!important;border-color:rgba(139,92,246,0.3)!important;background:rgba(139,92,246,0.08)!important}
        .btn-remix:hover{background:rgba(139,92,246,0.2)!important;border-color:var(--prim)!important}
        .actions{display:flex;gap:0.8rem;width:100%;flex-wrap:wrap;justify-content:center}
        .btn-create{display:inline-flex;align-items:center;gap:0.6rem;padding:1rem 2rem;background:linear-gradient(135deg,var(--prim),var(--sec));color:white;border-radius:14px;font-weight:700;font-size:1rem;text-decoration:none;box-shadow:0 8px 30px rgba(139,92,246,0.4);transition:all 0.3s;border:none;cursor:pointer;flex:1;justify-content:center;min-width:220px}
        .btn-create:hover{transform:translateY(-3px);box-shadow:0 12px 40px rgba(139,92,246,0.6)}
        .btn-download{display:inline-flex;align-items:center;gap:0.5rem;padding:1rem 1.5rem;background:rgba(255,255,255,0.08);border:1px solid var(--border);color:var(--text);border-radius:14px;font-weight:600;font-size:0.9rem;text-decoration:none;transition:all 0.2s;cursor:pointer;flex:1;justify-content:center;min-width:160px}
        .btn-download:hover{background:rgba(255,255,255,0.15);border-color:var(--prim)}
        .secondary-actions{display:flex;gap:0.6rem;flex-wrap:wrap;justify-content:center}
        .btn-secondary{display:inline-flex;align-items:center;gap:0.5rem;padding:0.65rem 1.3rem;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.08);color:var(--muted);border-radius:12px;font-weight:600;font-size:0.8rem;text-decoration:none;transition:all 0.2s}
        .btn-secondary:hover{background:rgba(255,255,255,0.1);color:var(--text);border-color:var(--border)}
        .cta-section{text-align:center;display:flex;flex-direction:column;align-items:center;gap:0.6rem;padding:1.5rem;background:var(--surf2);border-radius:20px;border:1px solid var(--border);width:100%}
        .cta-title{font-size:1.5rem;font-weight:800;line-height:1.3;background:linear-gradient(135deg,#fff 30%,var(--prim));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
        .cta-sub{font-size:0.9rem;color:var(--muted);line-height:1.5}

        /* RECENT GRID 6 IMAGES */
        .recent-section{width:100%;max-width:640px;display:flex;flex-direction:column;gap:1rem}
        .recent-header{text-align:center;display:flex;flex-direction:column;gap:0.3rem}
        .recent-title{font-size:1.1rem;font-weight:700}
        .recent-sub{font-size:0.8rem;color:var(--muted)}
        .recent-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:0.6rem}
        .recent-card{display:block;border-radius:12px;overflow:hidden;border:1px solid var(--border);transition:all 0.2s;aspect-ratio:1;position:relative}
        .recent-card:hover{border-color:var(--prim);transform:scale(1.03);box-shadow:0 8px 24px rgba(139,92,246,0.2)}
        .recent-card img{width:100%;height:100%;object-fit:cover}

        .footer{padding:1.5rem;text-align:center;font-size:0.7rem;color:var(--muted);border-top:1px solid var(--border);margin-top:auto}
        .footer a{color:var(--prim);text-decoration:none;margin:0 0.3rem}
        .footer a:hover{text-decoration:underline}
        @media(max-width:400px){.cta-title{font-size:1.2rem}.btn-create,.btn-download{padding:0.85rem 1rem;font-size:0.85rem;min-width:auto}.recent-grid{grid-template-columns:repeat(2,1fr)}.nav{padding:0.8rem 1rem}.interaction-bar{gap:0.4rem}.btn-interact{padding:0.6rem 1rem;font-size:0.8rem}}
    </style>
</head>
<body>
    <nav class="nav">
        <a href="${URLS.home}" class="nav-logo">
            <svg viewBox="0 0 32 32" fill="none"><defs><linearGradient id="sg" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#8B5CF6"/><stop offset="100%" stop-color="#EC4899"/></linearGradient></defs><path d="M16 2L28 10L24 28H8L4 10L16 2Z" fill="url(#sg)" stroke="rgba(255,255,255,0.15)" stroke-width="0.5"/><path d="M16 2L4 10L16 14L16 2Z" fill="rgba(255,255,255,0.2)"/></svg>
            <span>IA Pixora</span>
        </a>
        <div class="nav-links">
            <a href="${URLS.home}">${t.nav_home}</a>
            <a href="${URLS.gallery}">${t.nav_gallery}</a>
            <a href="${URLS.shop}">${t.nav_shop}</a>
            <a href="${URLS.profile}" class="nav-login">${t.nav_profile}</a>
        </div>
    </nav>

    <div class="main">
        <div class="container">
            <div class="badge-free"><i class="fas fa-check-circle"></i> ${t.badge}</div>

            <div class="image-wrapper">
                <img src="${imgUrl}" alt="AI Generated Image - IA Pixora" onclick="window.open('${imgUrl}','_blank')" onerror="this.parentElement.innerHTML='<p style=\\'padding:2rem;color:var(--muted);text-align:center\\'>${t.error}</p>'">
            </div>
            <!-- INTERACTION BAR: Like / Comment / Remix -->
            <div class="interaction-bar">
                <button class="btn-interact" onclick="toggleLike(this)" data-img="${encodeURIComponent(imgUrl)}">
                    <i class="fas fa-heart"></i> ${t.like} <span class="count" id="like-count">0</span>
                </button>
                <a href="${URLS.gallery}" class="btn-interact">
                    <i class="fas fa-comment-dots"></i> ${t.comment} <span class="count">0</span>
                </a>
                <a href="${URLS.home}?remix=${encodeURIComponent(imgUrl)}" class="btn-interact btn-remix">
                    <i class="fas fa-wand-magic-sparkles"></i> ${t.remix}
                </a>
            </div>

            <div class="actions">
                <a href="${URLS.home}" class="btn-create"><i class="fas fa-wand-magic-sparkles"></i> ${t.btn_create}</a>
                <button class="btn-download" onclick="downloadImage('${imgUrl}')"><i class="fas fa-download"></i> ${t.btn_download}</button>
            </div>

            <div class="secondary-actions">
                <a href="${URLS.gallery}" class="btn-secondary"><i class="fas fa-images"></i> ${t.btn_gallery}</a>
                <a href="${URLS.shop}" class="btn-secondary"><i class="fas fa-store"></i> ${t.btn_shop}</a>
                <a href="${URLS.earn}" class="btn-secondary"><i class="fas fa-coins"></i> ${t.btn_earn}</a>
            </div>

            <div class="cta-section">
                <h2 class="cta-title">${t.cta_title}</h2>
                <p class="cta-sub">${t.cta_sub}</p>
                <a href="${URLS.home}" class="btn-create" style="margin-top:0.5rem;padding:0.8rem 1.8rem;font-size:0.9rem"><i class="fas fa-sparkles"></i> ${t.btn_create}</a>
            </div>
        </div>

        <!-- 6 RECENT COMMUNITY CREATIONS -->
        <div class="recent-section">
            <div class="recent-header">
                <h3 class="recent-title">${t.more_title}</h3>
                <p class="recent-sub">${t.more_sub}</p>
            </div>
            <div class="recent-grid">
                ${recentCards}
            </div>
        </div>
    </div>

    <footer class="footer">
        © 2026 IA Pixora · <a href="${URLS.privacy}">${t.footer_privacy}</a> · <a href="${URLS.guide}">${t.footer_guide}</a> · <a href="${URLS.faq}">${t.footer_faq}</a>
    </footer>

    <script>
        function downloadImage(url){fetch(url).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='ia-pixora-'+Date.now()+'.png';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u)}).catch(()=>window.open(url,'_blank'))}
        function toggleLike(btn){
            const key='pixora_like_'+btn.dataset.img;
            const liked=localStorage.getItem(key)==='1';
            const countEl=btn.querySelector('#like-count');
            let count=parseInt(countEl.textContent)||0;
            if(!liked){
                localStorage.setItem(key,'1');
                btn.classList.add('liked');
                countEl.textContent=count+1;
            }else{
                localStorage.removeItem(key);
                btn.classList.remove('liked');
                countEl.textContent=Math.max(0,count-1);
            }
        }

        // Restore like state on load
        document.addEventListener('DOMContentLoaded',function(){
            const btn=document.querySelector('.btn-interact[data-img]');
            if(btn){
                const key='pixora_like_'+btn.dataset.img;
                if(localStorage.getItem(key)==='1'){
                    btn.classList.add('liked');
                    const c=btn.querySelector('#like-count');
                    if(c)c.textContent=parseInt(c.textContent)+1;
                }
            }
        });
    </script>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.status(200).send(html);
}
